const EVENT_DATA = [
  {
    id: "EVENT-51dfd8de",
    name: "badminton",
    min_players: 4,
    max_players: 5,
    reg_fee_per_player: 800,
    category: "men",
  },
  {
    id: "EVENT-dd1fb81a",
    name: "badminton",
    min_players: 2,
    max_players: 3,
    reg_fee_per_player: 800,
    category: "women",
  },
  {
    id: "EVENT-52ac13f2",
    name: "basketball",
    min_players: 7,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "men",
  },
  {
    id: "EVENT-48dfc044",
    name: "basketball",
    min_players: 7,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "women",
  },
  {
    id: "EVENT-ae4a382f",
    name: "cricket",
    min_players: 11,
    max_players: 16,
    reg_fee_per_player: 750,
    category: "men",
  },
  {
    id: "EVENT-3225d373",
    name: "chess",
    min_players: 4,
    max_players: 6,
    reg_fee_per_player: 300,
    category: "team",
  },
  {
    id: "EVENT-f7378799",
    name: "football",
    min_players: 11,
    max_players: 16,
    reg_fee_per_player: 750,
    category: "men",
  },
  {
    id: "EVENT-fdad56c3",
    name: "hockey",
    min_players: 11,
    max_players: 16,
    reg_fee_per_player: 750,
    category: "men",
  },
  {
    id: "EVENT-88aad1b8",
    name: "squash",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 400,
    category: "men",
  },
  {
    id: "EVENT-dfb6011d",
    name: "squash",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 400,
    category: "women",
  },
  {
    id: "EVENT-42dca38c",
    name: "table-tennis",
    min_players: 3,
    max_players: 4,
    reg_fee_per_player: 450,
    category: "men",
  },
  {
    id: "EVENT-472c15c2",
    name: "table-tennis",
    min_players: 2,
    max_players: 3,
    reg_fee_per_player: 400,
    category: "women",
  },
  {
    id: "EVENT-0a72270e",
    name: "tennis",
    min_players: 3,
    max_players: 4,
    reg_fee_per_player: 900,
    category: "men",
  },
  {
    id: "EVENT-ce127344",
    name: "tennis",
    min_players: 2,
    max_players: 3,
    reg_fee_per_player: 600,
    category: "women",
  },
  {
    id: "EVENT-f62cd99a",
    name: "volleyball",
    min_players: 6,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "men",
  },
  {
    id: "EVENT-096f30fd",
    name: "volleyball",
    min_players: 6,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "women",
  },
  {
    id: "EVENT-ccc72559",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "under-56-kg",
  },
  {
    id: "EVENT-d20d8a1d",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "57-to-62-kg",
  },
  {
    id: "EVENT-1172c3f1",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "63-to-69-kg",
  },
  {
    id: "EVENT-a33d974d",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "70-to-77-kg",
  },
  {
    id: "EVENT-2e4d2fbb",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "above-77-kg",
  },
  {
    id: "EVENT-ea9465f6",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "under-56-kg",
  },
  {
    id: "EVENT-6cde3110",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "57-to-62-kg",
  },
  {
    id: "EVENT-2219f89f",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "63-to-69-kg",
  },
  {
    id: "EVENT-97a5d83f",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "70-to-77-kg",
  },
  {
    id: "EVENT-0deca33c",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "above-77-kg",
  },
];

export default EVENT_DATA;
