const EVENT_DATA = [
  {
    id: "EVNTAAFD2D",
    name: "badminton",
    min_players: 4,
    max_players: 5,
    reg_fee_per_player: 800,
    category: "men",
  },
  {
    id: "EVNTE309A8",
    name: "badminton",
    min_players: 2,
    max_players: 3,
    reg_fee_per_player: 800,
    category: "women",
  },
  {
    id: "EVNT338D6D",
    name: "basketball",
    min_players: 7,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "men",
  },
  {
    id: "EVNTBB354B",
    name: "basketball",
    min_players: 7,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "women",
  },
  {
    id: "EVNT88A62B",
    name: "cricket",
    min_players: 11,
    max_players: 16,
    reg_fee_per_player: 750,
    category: "men",
  },
  {
    id: "EVNTD414E9",
    name: "chess",
    min_players: 4,
    max_players: 6,
    reg_fee_per_player: 300,
    category: "team",
  },
  {
    id: "EVNT8D3A52",
    name: "football",
    min_players: 11,
    max_players: 16,
    reg_fee_per_player: 750,
    category: "men",
  },
  {
    id: "EVNTDB09CF",
    name: "hockey",
    min_players: 11,
    max_players: 16,
    reg_fee_per_player: 750,
    category: "men",
  },
  {
    id: "EVNT82E89E",
    name: "squash",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 400,
    category: "men",
  },
  {
    id: "EVNT39A0F7",
    name: "squash",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 400,
    category: "women",
  },
  {
    id: "EVNTB0F458",
    name: "table-tennis",
    min_players: 3,
    max_players: 4,
    reg_fee_per_player: 450,
    category: "men",
  },
  {
    id: "EVNT92F9AE",
    name: "table-tennis",
    min_players: 2,
    max_players: 3,
    reg_fee_per_player: 400,
    category: "women",
  },
  {
    id: "EVNT49A7B0",
    name: "tennis",
    min_players: 3,
    max_players: 4,
    reg_fee_per_player: 900,
    category: "men",
  },
  {
    id: "EVNTA86088",
    name: "tennis",
    min_players: 2,
    max_players: 3,
    reg_fee_per_player: 600,
    category: "women",
  },
  {
    id: "EVNT18AC6B",
    name: "volleyball",
    min_players: 6,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "men",
  },
  {
    id: "EVNT1A179C",
    name: "volleyball",
    min_players: 6,
    max_players: 12,
    reg_fee_per_player: 300,
    category: "women",
  },
  {
    id: "EVNT80B489",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "under-56-kg",
  },
  {
    id: "EVNTD24F1D",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "57-to-62-kg",
  },
  {
    id: "EVNT10B8A4",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "63-to-69-kg",
  },
  {
    id: "EVNT31A7FC",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "70-to-77-kg",
  },
  {
    id: "EVNTE17860",
    name: "weightlifting",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 400,
    category: "above-77-kg",
  },
  {
    id: "EVNTA4D0AC",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "under-56-kg",
  },
  {
    id: "EVNT33F2A5",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "57-to-62-kg",
  },
  {
    id: "EVNTC9C0D7",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "63-to-69-kg",
  },
  {
    id: "EVNTFA797B",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "70-to-77-kg",
  },
  {
    id: "EVNTAECB50",
    name: "powerlifting",
    min_players: 1,
    max_players: 99,
    reg_fee_per_player: 300,
    category: "above-77-kg",
  },
  {
    id: "EVNTC526AD",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "100m-men",
  },
  {
    id: "EVNT5CC04A",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "200m-men",
  },
  {
    id: "EVNT3761F9",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "400m-men",
  },
  {
    id: "EVNT97D368",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "800m-men",
  },
  {
    id: "EVNT1F04F7",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "1500m-men",
  },
  {
    id: "EVNT9EEE7F",
    name: "athletics",
    min_players: 4,
    max_players: 4,
    reg_fee_per_player: 100,
    category: "4x100m-men",
  },
  {
    id: "EVNT096024",
    name: "athletics",
    min_players: 4,
    max_players: 4,
    reg_fee_per_player: 100,
    category: "4x400m-men",
  },
  {
    id: "EVNTE4A5BA",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "110m-hurdles-men",
  },
  {
    id: "EVNT2419E2",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "400m-hurdles-men",
  },
  {
    id: "EVNT238C4B",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "long-jump-men",
  },
  {
    id: "EVNT9EDCD9",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "high-jump-men",
  },
  {
    id: "EVNT22C2BC",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "triple-jump-men",
  },
  {
    id: "EVNT938A19",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "shotput-men",
  },
  {
    id: "EVNTAC9FE4",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "hammer-throw-men",
  },
  {
    id: "EVNTBFA7A4",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "javelin-men",
  },
  {
    id: "EVNTBDE3F3",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "discuss-throw-men",
  },
  {
    id: "EVNT49A8D4",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "100m-women",
  },
  {
    id: "EVNTF74181",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "200m-women",
  },
  {
    id: "EVNT88E4DC",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "400m-women",
  },
  {
    id: "EVNT3B1E32",
    name: "athletics",
    min_players: 4,
    max_players: 4,
    reg_fee_per_player: 100,
    category: "4x100m-women",
  },
  {
    id: "EVNT78C7D8",
    name: "athletics",
    min_players: 4,
    max_players: 4,
    reg_fee_per_player: 100,
    category: "4x400m-women",
  },
  {
    id: "EVNTFC7AC3",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "long-jump-women",
  },
  {
    id: "EVNT24E03C",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "high-jump-women",
  },
  {
    id: "EVNT6A44DE",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "shotput-women",
  },
  {
    id: "EVNT05E894",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "javelin-women",
  },
  {
    id: "EVNTF71528",
    name: "athletics",
    min_players: 1,
    max_players: 2,
    reg_fee_per_player: 200,
    category: "discuss-throw-women",
  },
];

export default EVENT_DATA;
