const TEAM_DATA = {
  "EXECUTIVE HEADS": [
    {
      name: "Soujanya Nayak",
      image: null,
      designation: "General Secretary: Sports and Games",
      phone: 7506136455,
      email: "soujanya4013@gmail.com",
    }, 
    {
      name: "SSVKSS Jyothiraditya",
      image: null,
      designation: "General Secretary: Sports and Games",
      phone: 7675007236,
      email: "adityagaikwad@kgpian.iitkgp.ac.in",
    }
  ],
  HEADS: [
    {
      name: "Aditya G Gaikwad",
      image: null,
      designation: "Sponsorship Head",
      phone: 9980090567,
      email: "adityagaikwad@kgpian.iitkgp.ac.in",
    },
    {
      name: "Akshat Dilip Lade",
      image: null,
      designation: "Sponsorship Head",
      phone: 9920378336,
      email: "akshatlade@kgpian.iitkgp.ac.in",
    },
    {
      name: "Akula Tejaswini",
      image: null,
      designation: "Logistics Head",
      phone: 7396066011,
      email: "akulatejaswini23@kgpian.iitkgp.ac.in",
    },
    {
      name: "Anushka Singh",
      image: null,
      designation: "Accomodation and Guest Reception Head",
      phone: 9335225142,
      email: "anushkasingh@kgpian.iitkgp.ac.in",
    },
    {
      name: "Archie Avirati",
      image: null,
      designation: "Events Head",
      phone: 7024385271,
      email: "archieavirati@kgpian.iitkgp.ac.in",
    },
    {
      name: "Atharva chilwarwar",
      image: null,
      designation: "Publicity and Marketings Head",
      phone: 7796557031,
      email: "Chilwarwar.atharva@kgpian.iitkgp.ac.in",
    },
    {
      name: "Chalamalla Sahithi",
      image: null,
      designation: "Sponsorship Head",
      phone: 6300290977,
      email: "sahithi@kgpian.iitkgp.ac.in",
    },
    {
      name: "Dhiya Mariam Thomas",
      image: null,
      designation: "Accomodation and Guest Reception Head",
      phone: "",
      email: "",
    },
    {
      name: "Gauransh Agarwal",
      image: null,
      designation: "Design Head",
      phone: 7063730072,
      email: "gauransh@kgpian.iitkgp.ac.in",
    },
    {
      name: "Harshvardhan Malla",
      image: null,
      designation: "Design Head",
      phone: 9392551557,
      email: "",
    },
    {
      name: "Himanshu Saini",
      image: null,
      designation: "Events Head",
      phone: 7348701571,
      email: "golusaini786@kgpian.iitkgp.ac.in",
    },
    {
      name: "Jatin Motwani",
      image: null,
      designation: "Finance Head",
      phone: 9424533623,
      email: "jatinmotwani@kgpian.iitkgp.ac.in",
    },
    {
      name: "Lokesh Agarwala",
      image: null,
      designation: "Finance Head",
      phone: 7728018715,
      email: "lokesh_agarwala@kgpian.iitkgp.ac.in",
    },
    {
      name: "Neeraj Patel",
      image: null,
      designation: "Logistics Head",
      phone: 7987752913,
      email: "neeraj.patel@kgpian.iitkgp.ac.in",
    },
    {
      name: "Nikhil Bharat Rajani",
      image: null,
      designation: "Events Head",
      phone: 7020096806,
      email: "nikhilrajani309@kgpian.iitkgp.ac.in",
    },
    {
      name: "Nimish Gadge",
      image: null,
      designation: "Sponsorship Head",
      phone: 9819755685,
      email: "nimishgadge@kgpian.iitkgp.ac.in",
    },
    {
      name: "Prajay",
      image: null,
      designation: "Sponsorship Head",
      phone: 9391738281,
      email: "mudavathprajay@kgpian.iitkgp.ac.in",
    },
    {
      name: "Prashant Tripathi",
      image: null,
      designation: "Publicity and Marketings Head",
      phone: 7398149866,
      email: "prashant@kgpian.iitkgp.ac.in",
    },
    {
      name: "Priyanshu Shaw",
      image: null,
      designation: "Events Head",
      phone: 9073808624,
      email: "priyanshushaw2807@kgpian.iitkgp.ac.in",
    },
    {
      name: "Raghuvar Srivastava",
      image: null,
      designation: "Sponsorship Head",
      phone: 9811097343,
      email: "raghuvarsrivastava@kgpian.iitkgp.ac.in",
    },
    {
      name: "Rishi Dhoble",
      image: null,
      designation: "Events Head",
      phone: 9205704432,
      email: "Rishisd@kgpian.iitkgp.ac.in",
    },
    {
      name: "Rohan R. Barsagade",
      image: null,
      designation: "Web Head",
      phone: 8263932614,
      email: "rohan842@kgpian.iitkgp.ac.in",
    },
    {
      name: "S.Siddharth",
      image: null,
      designation: "Publicity and Marketings Head",
      phone: 9789422444,
      email: "siddharthsabhari@kgpian.iitkgp.ac.in",
    },
    {
      name: "Sanyam Jhuria",
      image: null,
      designation: "Sponsorship Head",
      phone: 8078630257,
      email: "sanyamjhuria807@kgpian.iitkgp.ac.in",
    },
    {
      name: "Somyajeet Gupta Chowdhury",
      image: null,
      designation: "Web Head",
      phone: 9113340204,
      email: "somya.chowdhury@kgpian.iitkgp.ac.in",
    },
    {
      name: "Vaibhav Joshi",
      image: null,
      designation: "Design Head",
      phone: 9535734903,
      email: "vaibhav.joshi@kgpian.iitkgp.ac.in",
    },
    {
      name: "Vijeta Singh",
      image: null,
      designation: "Publicity and Marketings Head",
      phone: 7549585388,
      email: "Svijeta204@kgpian.iitkgp.ac.in",
    },
    {
      name: "Yashwanth Kumar Kallepalli",
      image: null,
      designation: "Publicity and Marketings Head",
      phone: 9347865123,
      email: "kyashwanth30@kgpian.iitkgp.ac.in",
    },
    {
      name: "Shubham Dilawar",
      image: null,
      designation: "Design Head",
      phone: "",
      email: "",
    },
  ],
};

export default TEAM_DATA;
