const TEAM_DATA = {
  "EXECUTIVE HEADS": [
    {
      name: "Soujanya Nayak",
      image: null,
      designation: "General Secretary: Sports and Games",
      email: "soujanya4013@gmail.com",
    }, 
    {
      name: "SSVKSS Jyothiraditya",
      image: null,
      designation: "General Secretary: Sports and Games",
      email: "jyothiraditya29@gmail.com",
    },
    {
      name: "Shreya Mishra",
      image: null,
      designation: "Institute Girl Sports Nominee",
      email: "mshreya1210@gmail.com",
    },
  ],
  HEADS: [
    {
      name: "Aditya G Gaikwad",
      image: null,
      designation: "Sponsorship Head",
      email: "adityagaikwad@kgpian.iitkgp.ac.in",
    },
    {
      name: "Akshat Dilip Lade",
      image: null,
      designation: "Sponsorship Head",
      email: "akshatlade@kgpian.iitkgp.ac.in",
    },
    {
      name: "Akula Tejaswini",
      image: null,
      designation: "Logistics Head",
      email: "akulatejaswini23@kgpian.iitkgp.ac.in",
    },
    {
      name: "Anushka Singh",
      image: null,
      designation: "Accomodation and Guest Reception Head",
      email: "anushkasingh@kgpian.iitkgp.ac.in",
    },
    {
      name: "Archie Avirati",
      image: null,
      designation: "Events Head",
      email: "archieavirati@kgpian.iitkgp.ac.in",
    },
    {
      name: "Atharva chilwarwar",
      image: null,
      designation: "Publicity and Marketings Head",
      email: "Chilwarwar.atharva@kgpian.iitkgp.ac.in",
    },
    {
      name: "Chalamalla Sahithi",
      image: null,
      designation: "Sponsorship Head",
      email: "sahithi@kgpian.iitkgp.ac.in",
    },
    {
      name: "Dhiya Mariam Thomas",
      image: null,
      designation: "Accomodation and Guest Reception Head",
      email: "",
    },
    {
      name: "Gauransh Agarwal",
      image: null,
      designation: "Design Head",
      email: "gauransh@kgpian.iitkgp.ac.in",
    },
    {
      name: "Harshvardhan Malla",
      image: null,
      designation: "Design Head",
      email: "",
    },
    {
      name: "Himanshu Saini",
      image: null,
      designation: "Events Head",
      email: "golusaini786@kgpian.iitkgp.ac.in",
    },
    {
      name: "Jatin Motwani",
      image: null,
      designation: "Finance Head",
      email: "jatinmotwani@kgpian.iitkgp.ac.in",
    },
    {
      name: "Lokesh Agarwala",
      image: null,
      designation: "Finance Head",
      email: "lokesh_agarwala@kgpian.iitkgp.ac.in",
    },
    {
      name: "Neeraj Patel",
      image: null,
      designation: "Logistics Head",
      email: "neeraj.patel@kgpian.iitkgp.ac.in",
    },
    {
      name: "Nikhil Bharat Rajani",
      image: null,
      designation: "Events Head",
      email: "nikhilrajani309@kgpian.iitkgp.ac.in",
    },
    {
      name: "Nimish Gadge",
      image: null,
      designation: "Sponsorship Head",
      email: "nimishgadge@kgpian.iitkgp.ac.in",
    },
    {
      name: "Prajay",
      image: null,
      designation: "Sponsorship Head",
      email: "mudavathprajay@kgpian.iitkgp.ac.in",
    },
    {
      name: "Prashant Tripathi",
      image: null,
      designation: "Publicity and Marketings Head",
      email: "prashant@kgpian.iitkgp.ac.in",
    },
    {
      name: "Priyanshu Shaw",
      image: null,
      designation: "Events Head",
      email: "priyanshushaw2807@kgpian.iitkgp.ac.in",
    },
    {
      name: "Raghuvar Srivastava",
      image: null,
      designation: "Sponsorship Head",
      email: "raghuvarsrivastava@kgpian.iitkgp.ac.in",
    },
    {
      name: "Rishi Dhoble",
      image: null,
      designation: "Events Head",
      email: "Rishisd@kgpian.iitkgp.ac.in",
    },
    {
      name: "Rohan R. Barsagade",
      image: null,
      designation: "Web Head",
      email: "rohan842@kgpian.iitkgp.ac.in",
    },
    {
      name: "S.Siddharth",
      image: null,
      designation: "Publicity and Marketings Head",
      email: "siddharthsabhari@kgpian.iitkgp.ac.in",
    },
    {
      name: "Sanyam Jhuria",
      image: null,
      designation: "Sponsorship Head",
      email: "sanyamjhuria807@kgpian.iitkgp.ac.in",
    },
    {
      name: "Somyajeet Gupta Chowdhury",
      image: null,
      designation: "Web Head",
      email: "somya.chowdhury@kgpian.iitkgp.ac.in",
    },
    {
      name: "Vaibhav Joshi",
      image: null,
      designation: "Design Head",
      email: "vaibhav.joshi@kgpian.iitkgp.ac.in",
    },
    {
      name: "Vijeta Singh",
      image: null,
      designation: "Publicity and Marketings Head",
      email: "Svijeta204@kgpian.iitkgp.ac.in",
    },
    {
      name: "Yashwanth Kumar Kallepalli",
      image: null,
      designation: "Publicity and Marketings Head",
      email: "kyashwanth30@kgpian.iitkgp.ac.in",
    },
    {
      name: "Shubham Dilawar",
      image: null,
      designation: "Design Head",
      email: "",
    },
  ],
};

export default TEAM_DATA;
